"""CORE TYPES — draft of embeddy/protocol/types.py (design file, NOT wired in).

NOTE ON FILENAME: kept as `core_types.py` in the spikes dir because a bare
`types.py` on sys.path shadows the stdlib `types` module and breaks every
import (verified empirically). At M1 this becomes `embeddy/protocol/types.py`
— a package-path import with no collision.

This file is a Phase-0 design artifact: it defines the typed records that
every protocol boundary (EmbeddingProvider, Searchable, pipeline, server)
must use. It will be moved verbatim to `embeddy/protocol/types.py` at M1,
then frozen at M4.

Invariants enforced here (CONCEPT §3.4, §5.1):
  * No `dict[str, Any]` crosses any protocol boundary.
  * Vector is float32, shape (dimension,), L2-normalized (cosine assumes
    unit vectors — CONCEPT §5.2).
  * Scores always carry their metric semantics (.metric).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import NewType, TypeAlias

import numpy as np

# ---------------------------------------------------------------------------
# Embed inputs
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ImageInput:
    """One image input, in a dependency-free transport encoding.

    `data` is the raw encoded bytes (PNG/JPEG/WebP); `mime` declares the
    encoding so a provider can decode to what its model needs (PIL, tensor,
    HF feature extractor). Keeping this at bytes/mime keeps embeddy core free
    of PIL and makes the HTTP path (base64 in the OpenAI-style wire shape)
    a pure conversion. Local providers decode lazily inside `encode`.
    """

    data: bytes
    mime: str  # e.g. "image/png"

    def __post_init__(self) -> None:
        if not self.mime.startswith("image/"):
            raise ValueError(f"mime must be image/*, got {self.mime!r}")


EmbedInput: TypeAlias = str | ImageInput
"""One embeddable input: plain text or one image (multimodal path, v1:
local-provider only per CONCEPT §7)."""


# ---------------------------------------------------------------------------
# Vectors — the unit of embedding output
# ---------------------------------------------------------------------------


class Metric(Enum):
    """The scoring metric a vector/distance came from. Scores are only
    meaningful relative to their metric (fixes the C3 class of bug)."""

    COSINE = "cosine"          # similarity in [0, 1]; 1 - cosine_distance
    BM25 = "bm25"              # FTS5 BM25 score (roughly <= 0)
    RRF = "rrf"                # fusion rank score, 1/(k+rank), k=60
    WEIGHTED = "weighted"      # min-max normalized blend of cosine + bm25
    RERANK = "rerank"          # cross-encoder score from the rerank stage


Vector: TypeAlias = np.ndarray
"""A single embedding: float32 ndarray, shape (dimension,), L2-normalized.

NewType is deliberately NOT used — numpy broadcasting and ufuncs don't play
well with NewType at runtime, and no runtime type checker enforces it anyway.
The invariant is enforced by construction: `normalize_l2()` below is the only
function that mints new vectors, and `assert_unit_vector()` is the guard on
the protocol boundary (every provider post-process, every store ingest).
"""


def normalize_l2(vec: np.ndarray) -> np.ndarray:
    """Return the L2-normalized float32 copy of `vec`. Raises on zero norm."""
    arr = np.asarray(vec, dtype=np.float32)
    if arr.ndim != 1:
        raise ValueError(f"Vector must be 1-D, got shape {arr.shape}")
    norm = float(np.linalg.norm(arr))
    if not np.isfinite(norm) or norm == 0.0:
        raise ValueError(f"cannot L2-normalize a zero/NaN vector (norm={norm})")
    return (arr / norm).astype(np.float32)


def assert_unit_vector(vec: Vector, *, tol: float = 1e-3) -> None:
    """Protocol guard: a vector crossing a boundary must be unit-norm."""
    norm = float(np.linalg.norm(vec))
    if not math.isclose(norm, 1.0, rel_tol=tol, abs_tol=tol):
        raise ValueError(f"expected unit-norm vector, got norm={norm:.6f}")


def cosine_similarity(a: Vector, b: Vector) -> float:
    """Cosine similarity of two unit vectors (dot product)."""
    assert_unit_vector(a)
    assert_unit_vector(b)
    return float(np.dot(a, b))


# ---------------------------------------------------------------------------
# Source identity & metadata (sources are first-class — CONCEPT §3.3)
# ---------------------------------------------------------------------------

SourceId: TypeAlias = str
"""Stable identifier of a source within a collection.

Type alias (not NewType) so sqlite and Qdrant backends can share the same
shaping. The sqlite backend stores it as the sources.id TEXT PRIMARY KEY and
uses it as the chunks.source_id FK value. The UUID-ish string is generated by
the pipeline (hash of collection + path) so it is stable across re-ingests
and identical across backends.
"""


@dataclass(frozen=True, slots=True)
class SourceMetadata:
    """Immutable description of one indexed source (file/URL/text)."""

    id: SourceId
    collection_id: str
    path: str                  # canonical path within the collection
    content_hash: str          # chonkai-computed hash (sha256 hex)
    size_bytes: int
    mtime: datetime | None = None

    def __post_init__(self) -> None:
        if self.size_bytes < 0:
            raise ValueError(f"size_bytes must be >= 0, got {self.size_bytes}")
        if not self.content_hash:
            raise ValueError("content_hash must be non-empty")


# ---------------------------------------------------------------------------
# Chunks
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class StoredChunk:
    """One stored chunk row. Typed record — no dict[str, Any].

    `metadata` carries the FILTERABLE fields the Searchable backends compile
    into SQL pre-filters (CONCEPT §5.4 / H1). Chonkai's richer per-chunk
    metadata is truncated at this boundary to the fields embeddy knows how to
    filter and score on; anything else is the chunker's business and is not
    searchable (documented, not silently dropped — see M4 filters work item).
    """

    id: str                    # unique chunk id: f"{source_id}:{seq}"
    collection_id: str
    source_id: SourceId
    content: str               # non-empty (ValidatedChunker invariant)
    chunk_type: str            # "paragraph" | "heading" | "function" | ...
    start_line: int            # 1-based, inclusive
    end_line: int              # 1-based, inclusive
    parent: str | None = None  # enclosing heading / definition name
    granularity: str | None = None  # "module" | "class" | "function" | None
    token_count: int = 0
    vector: Vector | None = None  # present only in add() payloads

    def __post_init__(self) -> None:
        if not self.content.strip():
            raise ValueError("StoredChunk content must be non-empty")
        if self.start_line < 1 or self.end_line < self.start_line:
            raise ValueError(
                f"invalid line range ({self.start_line}-{self.end_line})"
            )


# ---------------------------------------------------------------------------
# Search results & collection stats
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ScoredDocument:
    """One ranked hit. `.metric` declares what `.score` means — consumers
    must never treat scores across metrics as comparable (CONCEPT §3.4)."""

    chunk_id: str
    collection_id: str
    source_id: SourceId
    source_path: str
    content: str
    score: float
    metric: Metric

    def __post_init__(self) -> None:
        if not math.isfinite(self.score):
            raise ValueError(f"score must be finite, got {self.score}")


@dataclass(frozen=True, slots=True)
class CollectionStats:
    """Cheap, honest collection statistics (the `stats()` result)."""

    collection_id: str
    chunk_count: int
    source_count: int
    vector_dimension: int      # the RESOLVED dimension the collection stores
    size_bytes: int = 0
    last_updated: datetime | None = None


# ---------------------------------------------------------------------------
# chonkai -> embeddy image flow (the no-import rule, in one paragraph)
# ---------------------------------------------------------------------------

# chonkai owns document parsing, so images extracted from PDF/DOCX/HTML live
# on chonkai's OWN models (a chonkai Attachment = kind + bytes + mime + span),
# never on embeddy types — chonkai never imports embeddy. embeddy's pipeline
# consumes chonkai's public models and, at the embed step, converts each
# chonkai Attachment whose kind is image into an embeddy EmbedInput/ImageInput
# by copying (bytes, mime) — a value-level handoff through the pipeline
# function that depends on chonkai, not through any shared type or import.
# The provider then decodes those bytes lazily. Result: chonkai is a pure
# document layer with zero knowledge of embeddings, and the multimodal path
# is a plain adapter in embeddy (CONCEPT §4.1, §7 "local-provider only in v1").
